version: '3.9'

services:
  db:
    image: mariadb:10.6
    container_name: glpi-db
    hostname: glpi-db
    restart: always
    networks:
      - glpi
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    image: diouxx/glpi:latest
    container_name: glpi-app
    hostname: glpi-app
    restart: always
    networks:
      - glpi
    depends_on:
      - db
    # ports:
    #   - "80:80"
    environment:
      DB_HOST: glpi-db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - glpi_files:/var/www/html/glpi/files
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=adminproxy"
      # glpi en HTTP sur glpi.iris.a3n.fr:8080
      - "traefik.http.routers.glpi.entrypoints=web"
      - "traefik.http.routers.glpi.rule=Host(`glpi.${DOMAIN_NAME}`)"
      - "traefik.http.routers.glpi.service=glpi"
      - "traefik.http.services.glpi.loadbalancer.server.port=80"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: glpi-phpmyadmin
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: admin
  #     PMA_PASSWORD: louka110

volumes:
  db_data:
  glpi_files:

networks:
  glpi: